# Generated by Django 5.1.5 on 2025-01-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicezone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
