# Generated by Django 5.1.5 on 2025-01-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicezone', '0002_audiofile_is_active_videofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceToText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
