# Generated by Django 5.1.5 on 2025-01-27 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicezone', '0003_voicetotext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voicetotext',
            name='file_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SentimentAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(help_text='Unique identifier for the audio file', max_length=255)),
                ('scores', models.JSONField(help_text='Sentiment scores (e.g., compound, neg, neu, pos)')),
                ('converted_text', models.TextField(help_text='Text transcribed from the audio file')),
                ('sentiment', models.CharField(help_text='Overall sentiment (e.g., happy, sad, neutral)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
