# Generated by Django 5.1.5 on 2025-02-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicezone', '0005_sentimenttypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimenttypes',
            name='sentiment_type',
            field=models.CharField(help_text='Overall sentiment (e.g., happy, sad, neutral)', max_length=255),
        ),
    ]
